{
  "hi": "https://drive.google.com/uc?export=download&id=17MNI_gDra5NIyij3HOutvel0mB4PSygW",
  "mk": "https://drive.google.com/uc?export=download&id=16qn1LuAWVsgSo6wXewRTh5ratYN8ucNF",
  "mk itin ": "https://drive.google.com/uc?export=download&id=16qn1LuAWVsgSo6wXewRTh5ratYN8ucNF",
  "mk itim": "https://drive.google.com/uc?export=download&id=16qn1LuAWVsgSo6wXewRTh5ratYN8ucNF",
  "morn": "https://drive.google.com/uc?export=download&id=16IUuZNdV3md2mT4BcZhuJMfokCanTevn",
  "moni": "https://drive.google.com/uc?export=download&id16IUuZNdV3md2mT4BcZhuJMfokCanTevn",
  "උදෑස": "https://drive.google.com/uc?export=download&id=16IUuZNdV3md2mT4BcZhuJMfokCanTevn",
  "උදැස": "https://drive.google.com/uc?export=download&id=16IUuZNdV3md2mT4BcZhuJMfokCanTevn",
  "ko oya": "https://drive.google.com/uc?export=download&id=16MtgtmFPndiXrPIFBONtdU6qy3iAqSnr",
  "ko": "https://drive.google.com/uc?export=download&id=16MtgtmFPndiXrPIFBONtdU6qy3iAqSnr",
  "gn": "https://drive.google.com/uc?export=download&id=16DTGPY_Q2ygf1uKi_CD-hOI94OTMiJu-",
  "gd night":"https://drive.google.com/uc?export=download&id=16DTGPY_Q2ygf1uKi_CD-hOI94OTMiJu-",
  "මොකො": "https://drive.google.com/uc?export=download&id=17Kku_JRLVvQtHgIR5IqZiw6Oc0bVdYCf",
  "moko": "https://drive.google.com/uc?export=download&id=17Kku_JRLVvQtHgIR5IqZiw6Oc0bVdYCf",
  "හායි": "https://drive.google.com/uc?export=download&id=17MNI_gDra5NIyij3HOutvel0mB4PSygW",
  "හෙ": "https://drive.google.com/uc?export=download&id=17MNI_gDra5NIyij3HOutvel0mB4PSygW",
  "මොකද කරන්නෙ": "https://drive.google.com/uc?export=download&id=16qn1LuAWVsgSo6wXewRTh5ratYN8ucNF",
  "ගුඩ් නයිට්": "https://drive.google.com/uc?export=download&id=16DTGPY_Q2ygf1uKi_CD-hOI94OTMiJu-",
  "gm": "https://drive.google.com/uc?export=download&id=16IUuZNdV3md2mT4BcZhuJMfokCanTevn",
  "ගුඩ් මොනින්": "https://drive.google.com/uc?export=download&id=16IUuZNdV3md2mT4BcZhuJMfokCanTevn",
  "good morning": "https://drive.google.com/uc?export=download&id=16IUuZNdV3md2mT4BcZhuJMfokCanTevn",
  "ගුඩ් මොනිම්": "https://drive.google.com/uc?export=download&id=16IUuZNdV3md2mT4BcZhuJMfokCanTevn"
}
